- packages/core-sdk/src/resources/ipAsset.ts
Exposes `isNFTRegistered` to allow devs to check via SDK if an IP Account is registered for a given IP (NFT)
> Expose isNFTRegistered for IP Account registration check

- packages/core-sdk/package.json
- packages/core-sdk/src/utils/utils.ts
- pnpm-lock.yaml
Upgrade the `viem` version to ^2.7.0 and fix the type error.
Test results are available in the following snapshot.
- Unit tests
- integration Tests
> Upgrade the viem version to ^2.7.0

- .github/workflows/publish-package.yaml
- packages/core-sdk/package.json
Update the publish CI workflow to use the same logic as the internal testing. Later on we should reuse the same logic in build-and-test.yaml
> Update publish CI + Bump version

- package.json
- packages/core-sdk/package.json
- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/index.ts
- packages/core-sdk/src/resources/dispute.ts
- packages/core-sdk/src/resources/ipAccount.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/resources/nftClient.ts
- packages/core-sdk/src/resources/permission.ts
- packages/core-sdk/src/resources/royalty.ts
- packages/core-sdk/src/types/options.ts
- packages/core-sdk/src/types/resources/dispute.ts
- packages/core-sdk/src/types/resources/ipAccount.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/src/types/resources/license.ts
- packages/core-sdk/src/types/resources/nftClient.ts
- packages/core-sdk/src/types/resources/permission.ts
- packages/core-sdk/src/types/resources/royalty.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/wagmi-generator/sdk.ts
Merging from Dev to Main the following PRs
https://github.com/storyprotocol/sdk/pull/223
https://github.com/storyprotocol/sdk/pull/226
> Release 16 PR 

- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/index.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/src/types/resources/license.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/integration/license.test.ts
- packages/core-sdk/test/unit/resources/license.test.ts
- packages/wagmi-generator/wagmi.config.ts
- Return tokenId from mintAndRegisterIpAndMakeDerivative
- Add predictMintingLicenseFee to licensing module
- Add setLicenseConfig methods
> Add two methods and return tokenId from mintAndRegisterIpAndMakeDerivative

- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
Make `ipAsset.isRegistered` a public function. Previously, it was private.
> Feat/make isRegistered public

- packages/core-sdk/package.json
- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/index.ts
- packages/core-sdk/src/resources/group.ts
- packages/core-sdk/src/resources/ipAccount.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/permission.ts
- packages/core-sdk/src/types/resources/ipAccount.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/src/types/resources/permission.ts
- packages/core-sdk/src/utils/chain.ts
- packages/core-sdk/src/utils/sign.ts
- packages/core-sdk/test/integration/ipAccount.test.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/integration/permission.test.ts
- packages/core-sdk/test/unit/resources/ipAccount.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/core-sdk/test/unit/testUtils.ts
- packages/core-sdk/test/unit/utils/sign.test.ts
- packages/wagmi-generator/wagmi.config.ts
Methods included: 
- batchRegister
- BatchregisterDerivative 
- batchRegisterWithIpMetadata
- BatchMintAndRegisterIpAssetWithPilTerms 
- BatchmintAndRegisterIpAndMakeDerivative
Also export `getSignature` method, refactor how to calculate the deadline, and bump the version to 1.2.0-rc.2.
> Implement multicall 

- .github/CODEOWNERS
- packages/core-sdk/package.json
- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/index.ts
- packages/core-sdk/src/resources/group.ts
- packages/core-sdk/src/resources/ipAccount.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/permission.ts
- packages/core-sdk/src/types/resources/ipAccount.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/src/types/resources/permission.ts
- packages/core-sdk/src/utils/chain.ts
- packages/core-sdk/src/utils/sign.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/integration/permission.test.ts
- packages/core-sdk/test/unit/resources/ipAccount.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/core-sdk/test/unit/testUtils.ts
- packages/core-sdk/test/unit/utils/sign.test.ts
- packages/wagmi-generator/wagmi.config.ts
Features:
- Feat/make isRegistered public
- Add codeowners for pr review
- Implement multicall feature
> Bump up sdk version to 1.2.0-rc.2

- packages/core-sdk/package.json
- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/index.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- pnpm-lock.yaml
- Refactor registerIPAndAttachLicenseTermsAndDistributeRoyaltyTokens in the SDK #365
- Refactor mintAndRegisterIpAndAttachPILTermsAndDistributeRoyaltyTokens function #364
- Export the related types #355
- Updated to check whether the first license terms a commercial about `registerIPAndAttachLicenseTermsAndDistributeRoyaltyTokens` and `mintAndRegisterIpAndAttachPilTermsAndDistributeRoyaltyTokens`.
- Bump up version to 1.2.0-rc.4
> Enhance some features

- .github/workflows/pr-external.yaml
- .github/workflows/pr-internal.yml
- .github/workflows/publish-package.yaml
- packages/core-sdk/test/integration/permission.test.ts
* Migrated to `odyssey` environment and deprecating `beta-sepolia`
* Minor debug in permission integration tests
> Origin/dev polania/integration tests 2

- package.json
Iliad is no longer available so these tests will fail and block some CI flows. disabling for now until we fix these tests.
> fix: disable react-sdk integration tests

- packages/core-sdk/src/client.ts
- packages/core-sdk/src/index.ts
- packages/core-sdk/src/types/config.ts
- packages/core-sdk/src/types/options.ts
- packages/core-sdk/src/utils/chain.ts
- packages/core-sdk/src/utils/errors.ts
- packages/core-sdk/src/utils/utils.ts
- packages/core-sdk/test/integration/dispute.test.ts
- packages/core-sdk/test/integration/group.test.ts
- packages/core-sdk/test/integration/ipAccount.test.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/integration/license.test.ts
- packages/core-sdk/test/integration/permission.test.ts
- packages/core-sdk/test/integration/royalty.test.ts
- packages/core-sdk/test/integration/utils/mockERC20.ts
- packages/core-sdk/test/integration/utils/util.ts
- packages/core-sdk/test/unit/client.test.ts
- packages/core-sdk/test/unit/resources/dispute.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/permission.test.ts
- packages/core-sdk/test/unit/utils/sign.test.ts
- packages/core-sdk/test/unit/utils/utils.test.ts
- packages/wagmi-generator/wagmi.config.ts
Update `homer` in supported chains to `aeneid`, chain id remains the same. Explorer and rpc url is also updated.
Resolves #401
> feat: remove homer and add aeneid support

- packages/core-sdk/src/client.ts
- packages/core-sdk/src/constants/common.ts
- packages/core-sdk/src/resources/wip.ts
- packages/core-sdk/src/types/common.ts
- packages/core-sdk/src/types/options.ts
- packages/core-sdk/src/types/resources/wip.ts
- packages/core-sdk/src/types/utils/txOptions.ts
- packages/core-sdk/src/utils/txOptions.ts
- packages/core-sdk/test/integration/wip.test.ts
> feat: add WIP client

- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/resources/royalty.ts
- packages/core-sdk/src/types/resources/license.ts
- packages/core-sdk/src/types/resources/royalty.ts
- packages/core-sdk/test/integration/license.test.ts
- packages/core-sdk/test/integration/royalty.test.ts
- packages/core-sdk/test/unit/resources/license.test.ts
- packages/core-sdk/test/unit/resources/royalty.test.ts
This PR includes the following feature additions
- Adds `claimAllRevenue` to royalty module
- Add support for converting IP to WIP for `mintLicenseTokens` in license module and `payRoyaltyOnBehalf`
- Add support for transferring claimed revenue tokens to wallet and convert WIP -> IP on `claimAllRevenue`
> feat: New loyalty feature + WIP support for license and royalty

- packages/core-sdk/test/integration/ipAsset.test.ts
This PR adds edge cases and more complex tests to the `ipAsset` module integration tests.
> `ipAsset` integration tests - edge and complex cases

- packages/core-sdk/src/index.ts
- packages/core-sdk/src/types/utils/wip.ts
- packages/core-sdk/src/utils/wipFeeUtils.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- Export `WIP_TOKEN_ADDRESS`
- Add a safety check for WIP approval logic to ensure we never approve the Multicall contract as a spender.
> Export wip address & approval safety check

- packages/core-sdk/package.json
- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/resources/group.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/resources/nftClient.ts
- packages/core-sdk/src/types/common.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/src/utils/licenseTermsHelper.ts
- packages/core-sdk/test/integration/nftClient.test.ts
- packages/core-sdk/test/unit/mockData.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/nftClient.test.ts
- packages/core-sdk/test/unit/utils/licenseTermsHelper.test.ts
- packages/wagmi-generator/wagmi.config.ts
- `mintAndRegisterIp`: Pay nft minting fee
- `registerDerivative`
- `mintFeeToken`: Gets the mint fee token of an spg nft contract
- `mintFee`: Gets the mint fee of an spg nft contract
> Add new methods for nftClient

- packages/core-sdk/package.json
- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/index.ts
- packages/core-sdk/src/resources/royalty.ts
- packages/core-sdk/src/types/resources/royalty.ts
- packages/core-sdk/src/types/utils/wip.ts
- packages/core-sdk/src/utils/feeUtils.ts
- packages/core-sdk/src/utils/token.ts
- packages/core-sdk/test/integration/dispute.test.ts
- packages/core-sdk/test/integration/royalty.test.ts
- packages/core-sdk/test/unit/mockData.ts
- packages/core-sdk/test/unit/resources/group.test.ts
- packages/core-sdk/test/unit/resources/royalty.test.ts
- packages/core-sdk/test/unit/utils/feeUtils.test.ts
- packages/wagmi-generator/wagmi.config.ts
- Add `batchClaimAllRevenue` method
- Add `royalty` module unit tests
> Add batched claim all revenue method

- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/resources/dispute.ts
- packages/core-sdk/src/types/resources/dispute.ts
- packages/core-sdk/test/integration/dispute.test.ts
- packages/core-sdk/test/unit/resources/dispute.test.ts
- packages/wagmi-generator/wagmi.config.ts
Counters a dispute that was raised by another party on an IP using counter evidence that is uploaded to IPFS.
This method can only be called by the IP's owner to counter a dispute by providing counter evidence. The counter evidence (e.g., documents, images) should be uploaded to IPFS, and its corresponding CID is converted internally to a hash for the request.
```jsx
const ret = await client.dispute.disputeAssertion({
ipId, // the ipId of the disputed IP
assertionId, // the assertionId of the dispute
counterEvidenceCID, // CID of the counter evidence
});
```
> feat: Add dispute assertion to dispute client

- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/resources/royalty.ts
- packages/core-sdk/test/unit/resources/royalty.test.ts
- packages/wagmi-generator/wagmi.config.ts
- Add `executeBatch` instead of `execute` to batch all currency tokens
- Move out loop for `unwrapWipTokens` method
- Fix unit tests
> Refactor claim revenue

- packages/core-sdk/src/client.ts
- packages/core-sdk/src/resources/dispute.ts
- packages/core-sdk/src/resources/group.ts
- packages/core-sdk/src/resources/ipAccount.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/resources/nftClient.ts
- packages/core-sdk/src/resources/permission.ts
- packages/core-sdk/src/resources/royalty.ts
- packages/core-sdk/src/types/common.ts
- packages/core-sdk/src/types/resources/dispute.ts
- packages/core-sdk/src/types/resources/group.ts
- packages/core-sdk/src/types/resources/ipAccount.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/src/types/resources/license.ts
- packages/core-sdk/src/types/resources/nftClient.ts
- packages/core-sdk/src/types/resources/permission.ts
- packages/core-sdk/src/types/resources/royalty.ts
- packages/core-sdk/src/utils/getFunctionSignature.ts
- packages/core-sdk/src/utils/sign.ts
- Add inline docs to function request types
- Update all method jsdocs that have conflicting typescript tags (ie `@param`, `@return`)
- Update jsdocs for `claimAllRevenue` and `batchClaimAllRevenue`. We need to indicate that if there is no child ips (you are claiming only from the IP’s royalty vault), then you still need to populate `currencyTokens` with the tokens to claim.
The `getFunctionSignature` used `@param`,`@returns`, and `@throws`.  It's the util method, and the parameter is not an object. Do we need to remove it? @DracoLi
> Improve documentation

- .husky/pre-commit
- package.json
- pnpm-lock.yaml
Removes husky from the codebase. 
I've had a number of issues with our husky hook that runs `pnpm fix`. It slows down commits and also has the side effect of adding all local changes to a commit which most of the time I do not want.
The main functionality of the `pnpm fix` right now is running lint fix and prettier. However, this does not guarantee all committed code is formatted because it is possible to get around hooks. We should instead be using CI to check for formatting and lint issues and its the PR owner's responsibility to resolve them before merging in code.
> Remove husky

- packages/core-sdk/package.json
- packages/core-sdk/test/integration/dispute.test.ts
- packages/core-sdk/test/integration/utils/BIP32.ts
- pnpm-lock.yaml
This PR addresses the `AccountB` issue, which previously resulted in creating an unnecessary account and sending it 0.5 IP during tests that required two accounts. The earlier implementation relied on configuring two separate accounts within the `.env` file but was later modified to streamline the setup process for developers. However, the adopted method led to the creation and abandonment of multiple accounts containing small balances, cluttering the network unnecessarily.
The approach implemented in this PR uses `BIP32` to deterministically derive a extended private key (xpv) from the PK set in the `.env` file. It will fund the derived account if its balance goes under 5 IP and will set it up as `AccountB` for those tests requiring two accounts.
> `AccountB` issue fix

- packages/core-sdk/src/types/resources/dispute.ts
- packages/core-sdk/src/types/resources/ipAccount.ts
- packages/core-sdk/src/types/resources/nftClient.ts
- packages/core-sdk/src/utils/validateLicenseConfig.ts
1. Updated the `data` property in the following types from `Address` to `Hex`
- `CancelDisputeRequest`, `IPAccountExecuteRequest`, `IPAccountExecuteWithSigRequest`, `ResolveDisputeRequest`
2. Change `mintFeeToken` and `owner` in `CreateNFTCollectionRequest` from `Hex` to `Address` type.
> Fix incorrect address/hex types

- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/client.ts
- packages/core-sdk/src/index.ts
- packages/core-sdk/src/resources/royalty.ts
- packages/core-sdk/src/types/resources/royalty.ts
- packages/core-sdk/src/utils/royalty.ts
- packages/core-sdk/test/integration/group.test.ts
- packages/core-sdk/test/unit/resources/group.test.ts
- packages/core-sdk/test/unit/resources/royalty.test.ts
Transfers to vault an amount of revenue tokens claimable via a royalty policy.
```tsx
const result = await storyClient.royalty.transferToVault({
royaltyPolicy: NativeRoyaltyPolicy.LAP,
ipId,
ancestorIpId,
token: WIP_TOKEN_ADDRESS,
txOptions: { waitForTransaction: true },
});
```
> feat: add transferToVault to royalty client

- packages/core-sdk/src/types/resources/royalty.ts
Update jsdoc to fix the default value for ClaimAllRevenue options
> fix: invalid default value for claim options

- packages/core-sdk/src/resources/dispute.ts
- packages/core-sdk/test/integration/dispute.test.ts
need to make sure approve call finishes before executing the rest of the functions.
> fix: wait for tx in dispute approve call

- packages/core-sdk/test/integration/dispute.test.ts
Reverts https://github.com/storyprotocol/sdk/pull/480 since [this fix](https://github.com/storyprotocol/sdk/pull/482) should have resolved the initial issue.
> fix: revert test changes to disputeAssertion

- packages/core-sdk/src/resources/dispute.ts
- packages/core-sdk/test/integration/dispute.test.ts
1. When `useMulticallWhenPossible` is false and multiple data entries are passed, the function concurrently executes `tagIfRelatedIpInfringed`, resulting in the same nonce being used. The SDK only tests with a single data entry when `useMulticallWhenPossible` is set to `false`.
2. Modify the integration test about the max bond , because the configuration has changed.
> Fix tagIfRelatedIpInfringed method when useMulticallWhenPossible is false

- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
Fix the wrong spender from `royaltyTokenDistributionWorkflows` to `royaltyModule` in the `registerDerivative` method.
> Fix issue about registerDerivative method

- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/types/utils/wip.ts
- packages/core-sdk/src/utils/feeUtils.ts
- packages/core-sdk/src/utils/predictMintingLicenseFee.ts
- packages/core-sdk/test/integration/dispute.test.ts
- packages/core-sdk/test/integration/license.test.ts
- packages/core-sdk/test/integration/utils/BIP32.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/license.test.ts
- packages/core-sdk/test/unit/utils/validateLicenseConfig.test.ts
1. Refactor the attached license terms check from `mintLicenseTokens` . The license terms must be attached to the IP ID,  with two exceptions:
1. Default license terms can be minted without explicit attachment since they are automatically
2. IP owners have special privileges and can mint license tokens for their own IPs using any license terms, even if those terms are not explicitly attached.
2. Create the `getDerivedStoryClient` method to generate a derived story client in the integration test.
3. Fix bug when calling `predictMintingLicenseFee` method with default license id.
> Enhance mintLicenseTokens method

- packages/core-sdk/src/resources/license.ts
Default license terms no longer are attached to ip assets by default.
Updating mint tokens logic to ensure we check that parent has the license terms even if its the default terms.
> fix: remove default license check for mint license tokens

- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/resources/group.ts
- packages/core-sdk/src/types/resources/group.ts
- packages/core-sdk/test/integration/group.test.ts
- packages/core-sdk/test/unit/resources/group.test.ts
- packages/wagmi-generator/wagmi.config.ts
This PR implements the `addIpsToGroup` method in the group module, mirroring the functionality of the [Smart Contract `addIp` method](https://github.com/storyprotocol/protocol-core-v1/blob/main/contracts/modules/grouping/GroupingModule.sol#L149).
- Added `addIpsToGroup` method to the `group` module  
- Introduced corresponding `AddIpRequest` type in `group` types  
**Unit Tests Added:**  
- Validates error throwing for invalid IP addresses  
- Verifies successful transaction hash return  
**Integration Test Added:**  
- Ensures successful addition of multiple IPs to a group
> Add addIp method 

- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
If the SPG NFT contract's public minting is disabled, we need to check if the caller has the `minter role`.
When public minting is disabled, we can't use `multicall` because we need to perform additional role checks
that aren't compatible with batched transactions.
This is because role-based access control requires the transaction's `msg.sender` to be verified directly,
which is not preserved when using `multicall` (where the multicall contract becomes the sender).
The following methods will be checked:
- mintAndRegisterIpAssetWithPilTerms
- mintAndRegisterIpAndMakeDerivative
- mintAndRegisterIp
- mintAndRegisterIpAndMakeDerivativeWithLicenseTokens
- mintAndRegisterIpAndAttachPilTermsAndDistributeRoyaltyTokens
- mintAndRegisterIpAndMakeDerivativeAndDistributeRoyaltyTokens
Add the …
> Add support for public minting checks in IP asset registration

- packages/core-sdk/test/integration/nftClient.test.ts
This PR expands coverage for the `nftClient` module, more specifically for the `setTokenURI` function.
> NftClient  Integration Test - `setTokenURI`

- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/types/resources/license.ts
- packages/core-sdk/src/utils/licenseTermsHelper.ts
- packages/core-sdk/test/integration/license.test.ts
- packages/core-sdk/test/unit/resources/license.test.ts
- packages/core-sdk/test/unit/utils/licenseTermsHelper.test.ts
1. Add `registerCreativeCommonsAttributionPIL` method 
2. Refactor register licenses with different types and extract a common method, which is the `registerPILTermsHelper`.
The pr belongs to `SDK v1.3.2.`
> Add creative commons attribution method

- packages/core-sdk/src/client.ts
- packages/core-sdk/src/resources/group.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/resources/permission.ts
- packages/core-sdk/src/types/config.ts
- packages/core-sdk/src/types/resources/permission.ts
- packages/core-sdk/src/utils/sign.ts
- packages/core-sdk/src/utils/utils.ts
- packages/core-sdk/test/integration/utils/util.ts
- packages/core-sdk/test/unit/mockData.ts
- packages/core-sdk/test/unit/resources/dispute.test.ts
- packages/core-sdk/test/unit/resources/group.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/license.test.ts
- packages/core-sdk/test/unit/resources/permission.test.ts
- packages/core-sdk/test/unit/resources/royalty.test.ts
- packages/core-sdk/test/unit/utils/sign.test.ts
- packages/core-sdk/test/unit/utils/utils.test.ts
- Make `chainId` a type of `number` instead of `string`.
- Remove `chain[this.chainId]` in many places
- Change `getPermissionSignature` and `getSignature` requests of the `chainId` of `ChainIds`
- Update `chainId` from `string | number | bigint` to `ChainIds` in `getPermissionSignature`  and  `getSignature` methods
- Update  `ChainIds` from `"1315" | "1514"` to `1315 | 1514` when initiating story client.
> Clean chain id usage

- .gitignore
- packages/core-sdk/.eslintrc.cjs
- packages/core-sdk/eslint.config.mjs
- packages/core-sdk/package.json
- packages/core-sdk/src/index.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/types/resources/royalty.ts
- packages/core-sdk/src/utils/registrationUtils/transformRegistrationRequest.ts
- packages/core-sdk/src/utils/utils.ts
- packages/eslint-config-story/index.js
- packages/eslint-config-story/package.json
- pnpm-lock.yaml
1. Update `ESLint` and related dependencies to the latest version. It starts using `Flat Config Files` instead of the previous configuration file.
2. Fix related lint issues
3. Move `dependency` packages into `devDependency ` packages in `@story-protocol/eslint-config`, because it's development packages.
4. Fix the warning when running `pnpm run fix` command
6. Add cursor config to `gitignore`
The next step is to add extra Linter Additions in the next PR.
> Upgrade ESLint to version 9.26.0

- packages/core-sdk/src/resources/ipAsset.ts
- packages/eslint-config-story/index.js
Enforcing a naming convention keeps the code base consistent and reduces overhead when naming variables. 
- Use `camelCase` and `UPPER_CASE`  for `variable`, `parameter`, and `function` names.
- Use `PascalCase` and `UPPER_CASE` for `enumMember` names and `enum` names.
- Use `PascalCase` for `typeLike`, such as the  `class`, `enum`, `interface`, `typeAlias`, `typeParameter`
```
"@typescript-eslint/naming-convention": [
"error",
{
selector: ["variable", "function", "parameter"],
format: ["camelCase", "UPPER_CASE"],
},
{
selector: ["enumMember", "enum"],
format: ["UPPER_CASE", "PascalCase"],
},
{
selector: ["typeLike"],
format: ["PascalCase"],
},
],
```
> Enforce naming conventions for variables, functions, and types

- packages/eslint-config-story/index.js
1. Using a single import statement per module will make the code clearer because you can see everything being imported from that module on one line.
Example of incorrect code for this rule:
```
import { merge } from 'module';
import something from 'another-module';
import { find } from 'module'; //error
```
2. Require default cases in switch statements
Example of incorrect code for this rule:
```
/*eslint default-case: "error"*/
switch (a) {
case 1:
/* code */
break;
}
```
3. Require the use of === and !==
Example of incorrect code for this rule:
```
if (x == 42) { }
```
4. Require const declarations for variables that are never reassigned after declared
Example of incorrect code for this rule:
```
// it's initialized and never reassigned.
let a = 3;
console.log(a);
```
> Add extra eslint rules

- packages/core-sdk/src/client.ts
- packages/core-sdk/src/resources/dispute.ts
- packages/core-sdk/src/resources/group.ts
- packages/core-sdk/src/resources/ipAccount.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/resources/nftClient.ts
- packages/core-sdk/src/resources/permission.ts
- packages/core-sdk/src/resources/royalty.ts
- packages/core-sdk/src/utils/calculateMintFee.ts
- packages/core-sdk/src/utils/feeUtils.ts
- packages/core-sdk/src/utils/licenseTermsHelper.ts
- packages/core-sdk/src/utils/oov3.ts
- packages/core-sdk/src/utils/registrationUtils/registerValidation.ts
- packages/core-sdk/src/utils/registrationUtils/transformRegistrationRequest.ts
- packages/core-sdk/src/utils/sign.ts
- packages/core-sdk/src/utils/token.ts
- packages/core-sdk/src/utils/utils.ts
- packages/core-sdk/src/utils/validateLicenseConfig.ts
- packages/eslint-config-story/index.js
- packages/eslint-config-story/package.json
- pnpm-lock.yaml
1. Install `stylistic` package( This `padding-line-between-statements` was deprecated in `ESLint` v8.53.0 and migrate into `stylistic`)
2. Add a blank line, follow the rule below: 
``` ts
"@stylistic/ts/padding-line-between-statements": [
"error",
{ blankLine: "always", prev: "function", next: "function" },
{ blankLine: "always", prev: "class", next: "class" },
{ blankLine: "always", prev: "interface", next: "interface" },
{ blankLine: "always", prev: "type", next: "type" },
{ blankLine: "always", prev: "block-like", next: "block-like" },
],
```
3. Fix lint error about space.
To reduce conflict, I rebased the `Add extract eslint rules` pr into the pr, so the code has some duplication.
> Add blank line between statements

- .github/workflows/pr-external.yaml
- .github/workflows/pr-internal.yml
- .github/workflows/publish-package.yaml
- packages/core-sdk/package.json
This PR fixes the current unit/integration tests workflow. 
* Sets integration tests only after a PR is submitted.
* Sets unit tests only after a push. 
* Fixes the issues with the notification to 57Blocks slack channel
> Test Workflow Improvements

- packages/core-sdk/package.json
- packages/core-sdk/src/index.ts
- packages/core-sdk/src/utils/oov3.ts
- packages/core-sdk/test/integration/dispute.test.ts
- packages/core-sdk/test/integration/utils/util.ts
- packages/core-sdk/test/unit/hooks.js
- packages/core-sdk/test/unit/hooks.ts
- packages/core-sdk/test/unit/utils/oov3.test.ts
-  Add the `settleAssertion` method
- Create `packages/core-sdk/test/unit/hooks.js` file, which will automatically run `restore`. Don't need to add test cases.
```
afterEach() {
sinon.restore();
},
```
> Add the settleAssertion method

- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/types/resources/dispute.ts
- packages/core-sdk/src/types/resources/group.ts
- packages/core-sdk/src/types/resources/ipAccount.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/src/types/resources/license.ts
- packages/core-sdk/src/types/resources/nftClient.ts
- packages/core-sdk/src/types/resources/permission.ts
- packages/core-sdk/src/types/resources/royalty.ts
- packages/core-sdk/src/types/resources/tagging.ts
- packages/core-sdk/test/unit/resources/license.test.ts
Fix `txHash` type from `string` and `Hex` into `txHash`.
Removing `txHash` when attachLicenseTerms given licenseTermsId is already attached. @bpolania, there is a breaking change, and we need to highlight it in the release notes.
> Fix txHash type

- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/resources/royalty.ts
- packages/core-sdk/src/types/options.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/src/types/resources/royalty.ts
- packages/core-sdk/src/types/resources/tagging.ts
- packages/core-sdk/src/types/utils/wip.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/license.test.ts
Remove all options (wipOptions, etc) into a single optional options property. Every public client method that accepts options should do this.
Put `wipOptions` and `erc20Options` under the `options` property.
This is a breaking change to require the SDK user to move `wipOptions` and `erc20Options` into `options`.
Before
```
await client.ipAsset.batchRegisterIpAssetsWithOptimizedWorkflows({
requests: requests,
wipOptions: {
useMulticallWhenPossible: false,
},
});
```
Now
```
await client.ipAsset.batchRegisterIpAssetsWithOptimizedWorkflows({
requests: requests,
options: {
wipOptions: {
useMulticallWhenPossible: false,
},
},
});
```
> Refactor wipOptions and erc20Options

- packages/core-sdk/eslint.config.mjs
- packages/core-sdk/tsconfig.json
- packages/eslint-config-story/index.js
In `packages/core-sdk`, there is the  `xx was not found by the project service. Consider either including it in the tsconfig.json or including it in allowDefaultProject` warning.
The pr fixes the warning.
> Fix lint waring

- packages/core-sdk/package.json
This PR introduces a patch version increment for the `@story-protocol/core-sdk` package.
- **Package:** `@story-protocol/core-sdk`
- **Previous Version:** `1.3.2`
- **New Version:** `1.3.3`
- **Change Type:** Patch (backward compatible)
- `packages/core-sdk/package.json` - Version number update
> chore: bump version to 1.3.3

- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/utils/pilFlavor.ts
- packages/core-sdk/src/utils/registrationUtils/registerValidation.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/license.test.ts
- packages/core-sdk/test/unit/utils/pilFlavor.test.ts
- Remove `getRevenueShare` utility  in `PILFlavor` and put it into the `validateLicenseTermsData` method
- Call the `getRevenueShare` method in the `registerPILTermsHelper`
- Add unit tests and integration tests in the following methods:
1. `mintAndRegisterIpAssetWithPilTerms`
2. `registerIpAndAttachPilTerms`
3. `registerPilTermsAndAttach`
4. `registerIPAndAttachLicenseTermsAndDistributeRoyaltyTokens`
5. `mintAndRegisterIpAndAttachPilTermsAndDistributeRoyaltyTokens`
6. `batchRegisterIpAssetsWithOptimizedWorkflows`
> Fix commercialRevShare re-transfer

- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- Add the linkDerivative method
- Add unit and integration tests
Since `registerDerivative` and `registerDerivativeWithLicenseTokens` keep the same structure as `linkDerivative`,
to stay consistent, keep the same type of `LinkDerivativeResponse`
- Change the `registerDerivative`'s response from `RegisterDerivativeResponse` to `LinkDerivativeResponse`
- Change the `registerDerivativeWithLicenseTokens` response from `RegisterDerivativeWithLicenseTokensResponse` to `LinkDerivativeResponse`
> feat: re-design the link Derivative method

- packages/core-sdk/src/resources/group.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/types/resources/group.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/src/types/resources/license.ts
- packages/core-sdk/src/utils/registrationUtils/registerValidation.ts
- packages/core-sdk/src/utils/validateLicenseConfig.ts
- packages/core-sdk/test/integration/group.test.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/integration/license.test.ts
- packages/core-sdk/test/unit/resources/group.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/license.test.ts
- packages/core-sdk/test/unit/utils/validateLicenseConfig.test.ts
In the following field, make it optional and give a default value:
- maxMintingFee: 0
- maxRts: 100*10**6
- maxRevenueShare: 100*10**6
- maxAllowedRewardShare: 100*10**6
- maxAllowedRewardSharePercentage: 100*10**6
And add related unit tests to coverage.
I don't give the default value of `expectMinimumGroupRewardShare`; I am not sure what value I should provide.
Confirmed with @jacob-tucker , we don't need to give the default value of `expectMinimumGroupRewardShare`.
> Add default values
