- .github/workflows/build-and-test.yaml
- .github/workflows/external-pr.yaml
- .github/workflows/internal-pr.yaml
* Add back CI workflows
* Use environment to separate secrets
> Add back CI workflows (#11)

- .gitmodules
- Makefile
- packages/core-sdk/src/abi/json/Errors.abi.ts
- packages/core-sdk/src/abi/json/Errors.json
- packages/core-sdk/src/abi/json/IPRecordRegistry.abi.ts
- packages/core-sdk/src/abi/sdkEntities.json
Change:
1. Add error abis
2. Add some event abis
> Add error and some event abis

- packages/core-sdk/src/client.ts
- packages/core-sdk/src/index.ts
- packages/core-sdk/src/resources/moduleReadOnly.ts
- packages/core-sdk/src/types/client.ts
- packages/core-sdk/src/types/resources/module.ts
- packages/core-sdk/test/integration/ipAccount.test.ts
- packages/core-sdk/test/integration/moduleReadOnly.test.ts
- packages/core-sdk/test/integration/platform.test.ts
- packages/core-sdk/test/unit/resources/moduleReadOnly.test.ts
Add ModuleReadOnlyClient:
- getter function: input a module name and output the module address
- list function: lists all modules
> Add ModuleReadOnlyClient

- packages/core-sdk/src/index.ts
- packages/core-sdk/src/resources/tagging.ts
- packages/core-sdk/src/utils/utils.ts
- packages/core-sdk/test/integration/dispute.test.ts
- packages/core-sdk/test/integration/tagging.test.ts
- packages/core-sdk/test/unit/resources/dispute.test.ts
- packages/core-sdk/test/unit/resources/tagging.test.ts
- Adds in wait for transaction feature in tagging module. (Previously missing)
- Exports types
> add waitTx and export types

- .github/workflows/publish-package.yaml
- packages/core-sdk/test/integration/policy.test.ts
* Update CI publish
* Disable policy test
> Update CI publish (#80)

- packages/core-sdk/test/unit/client.test.ts
- packages/core-sdk/test/unit/clients/storyAPI.test.ts
- packages/core-sdk/test/unit/resources/dispute.test.ts
- packages/core-sdk/test/unit/resources/ipAccount.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/license.test.ts
- packages/core-sdk/test/unit/resources/permission.test.ts
- packages/core-sdk/test/unit/resources/policy.test.ts
- packages/core-sdk/test/unit/utils/royaltyContext.test.ts
- packages/core-sdk/test/unit/utils/utils.test.ts
> add unit test cases

- packages/core-sdk/package.json
- packages/core-sdk/src/resources/dispute.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/resources/policy.ts
- packages/core-sdk/src/utils/utils.ts
- packages/core-sdk/test/integration/sepolia/ipAsset.sepolia.test.ts
- packages/core-sdk/test/integration/sepolia/license.sepolia.test.ts
- packages/core-sdk/test/integration/sepolia/policy.sepolia.test.ts
- packages/core-sdk/test/unit/resources/dispute.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/license.test.ts
- packages/core-sdk/test/unit/resources/policy.test.ts
* Update waitTxAndFilterLog
* Add filter logs by from
* Update testing
* bump up to rc8
> Update license minting event + bump up rc8 (#93)

- packages/core-sdk/README.md
- packages/core-sdk/package.json
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/test/integration/iipAsset.test.ts
Change:
1. Remove min royalty
2. Update Tests
3. Update README
> Remove min royalty and update tests

- packages/core-sdk/package.json
- packages/core-sdk/src/utils/utils.ts
- pnpm-lock.yaml
This update upgrades `viem` version from viem 1.x to viem 2.x
> Upgrade the viem version to ^2.7.0 (#101)

- packages/core-sdk/package.json
> update package version

- .github/workflows/external-pr.yaml
- .github/workflows/publish-package.yaml
1. Add external pr flow back
2. Remove the package.json check for the publich CI temporarily
> Add external CI back

- packages/core-sdk/src/abi/json/Errors.abi.ts
- packages/core-sdk/src/abi/json/Errors.json
- packages/core-sdk/src/abi/json/LicensingModule.abi.ts
- packages/core-sdk/src/abi/sdkEntities.json
- packages/core-sdk/src/index.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/src/types/resources/license.ts
- packages/core-sdk/test/integration/storyTestNet/ipAsset.storyTest.test.ts
- packages/core-sdk/test/integration/storyTestNet/license.storyTest.test.ts
- packages/core-sdk/test/integration/storyTestNet/royalty.storyTest.test.ts
Add ipAsset module methods including registerDerivative and registerDerivativeWithLicenseTokens
> Add ipAsset module methods including registerDerivative and registerDerivativeWithLicenseTokens

- packages/core-sdk/test/integration/storyTestNet/ipAsset.storyTest.test.ts
Skip ipAsset integration test in order to pass pipeline.
> Skip ipAsset integration test

- packages/core-sdk/package.json
- packages/core-sdk/src/types/options.ts
- pnpm-lock.yaml
> add maxFeePerGas to txOptions

- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/client.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/resources/royalty.ts
- packages/core-sdk/src/types/resources/royalty.ts
- packages/core-sdk/test/integration/storyTestNet/royalty.storyTest.test.ts
- packages/core-sdk/test/unit/client.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/core-sdk/test/unit/testUtils.ts
- packages/wagmi-generater/wagmi.config.ts
- Add unit tests about `register` and `registerDerivative`
- Add extra strict validation
> Add extra strict validation and ipAsset partial unit tests

- packages/core-sdk/package.json
- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/resources/royalty.ts
- packages/core-sdk/src/types/resources/royalty.ts
- packages/core-sdk/test/integration/storyTestNet/royalty.storyTest.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/license.test.ts
- packages/core-sdk/test/unit/resources/royalty.test.ts
- packages/wagmi-generater/wagmi.config.ts
1. Add royalty.claimRevenue method
2. Add unit tests including license, ipAsset, partial royalty module's unit tests
> Add royalty.claimRevenue method and unit tests

- packages/core-sdk/package.json
- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/client.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/resources/royalty.ts
- packages/core-sdk/src/types/resources/royalty.ts
- packages/core-sdk/test/integration/storyTestNet/royalty.storyTest.test.ts
- packages/core-sdk/test/unit/client.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/license.test.ts
- packages/core-sdk/test/unit/resources/royalty.test.ts
- packages/core-sdk/test/unit/testUtils.ts
- packages/wagmi-generater/wagmi.config.ts
1. Add more input validation for devEx optimization
2. Add claimRoyalty function
3. More unit tests
1. Integration test
2. Unit test
> 1.0.0.-rc4

- packages/core-sdk/package.json
- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/client.ts
- packages/core-sdk/src/resources/dispute.ts
- packages/core-sdk/src/resources/ipAccount.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/resources/permission.ts
- packages/core-sdk/src/resources/royalty.ts
- packages/core-sdk/src/types/config.ts
- packages/core-sdk/src/utils/utils.ts
- packages/core-sdk/test/integration/dispute.test.ts
- packages/core-sdk/test/integration/license.test.ts
- packages/core-sdk/test/integration/util.ts
- packages/core-sdk/test/unit/utils/utils.test.ts
- packages/wagmi-generater/package.json
- packages/wagmi-generater/wagmi.config.ts
- pnpm-lock.yaml
- Update contract address and add env config about apiKey
- Hide story net
> Update contract address and hide story net

- packages/core-sdk/src/resources/royalty.ts
- packages/core-sdk/src/types/resources/royalty.ts
1. Fix capitol letter in ClaimRevenueRequest and ClaimRevenueResponse
2. Added param description for missing `account` in ClaimRevenueRequest. Is this the correct description?
> small fixes

- packages/core-sdk/package.json
- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/index.ts
- packages/core-sdk/src/resources/ipAccount.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/resources/royalty.ts
- packages/core-sdk/src/types/common.ts
- packages/core-sdk/src/types/resources/ipAccount.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/src/types/resources/license.ts
- packages/core-sdk/src/types/resources/royalty.ts
- packages/core-sdk/src/utils/getLicenseTermsByType.ts
- packages/core-sdk/src/utils/utils.ts
- packages/core-sdk/test/integration/ipAccount.test.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/integration/license.test.ts
- packages/core-sdk/test/integration/permission.test.ts
- packages/core-sdk/test/integration/royalty.test.ts
- packages/core-sdk/test/unit/resources/license.test.ts
- packages/core-sdk/test/unit/resources/royalty.test.ts
- packages/core-sdk/test/unit/utils/getLicenseTermsByType.test.ts
- packages/wagmi-generater/wagmi.config.ts
The following three issues have been fixed:
- Add getLicenseTerms in [issue1](https://github.com/storyprotocol/sdk/issues/151)
- ClaimRevenue by EOA [issue2](https://github.com/storyprotocol/sdk/issues/156)
- Add two methods about spg
- unit tests
Note: IpAsset contains two spg methods that are in progress, so I'm not adding unit tests.
- integration tests
- [issue1](https://github.com/storyprotocol/sdk/issues/151)
- [issue2](https://github.com/storyprotocol/sdk/issues/156)
> Fix two issues including getLicenseTerms and claimRevenue by EOA

- packages/core-sdk/package.json
> Bump version to 1.0.0-rc.8

- .github/workflows/publish-package.yaml
Example:
- 2. ...
Example: 
- 2. ...
> [fix] add condition check back

- packages/core-sdk/src/index.ts
Exports `SupportedChainIds` type
> export SupportedChainIds

- .github/workflows/build-and-test.yaml
> Update Anvil CI

- .github/workflows/pr-internal.yml
This PR fixes the issue related to the internal workflow got triggered by an external PR.
> [fix] disable internal workflow for external pr

- packages/core-sdk/src/types/options.ts
No code changes. Just added comments to `options.ts` so that we can point there for better documentation.
> Add comments for txoptions

- packages/core-sdk/src/resources/ipAccount.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/resources/nftClient.ts
- packages/core-sdk/src/resources/permission.ts
- packages/core-sdk/src/resources/royalty.ts
- packages/core-sdk/src/types/resources/ipAccount.ts
- packages/core-sdk/src/types/resources/license.ts
- packages/core-sdk/src/utils/sign.ts
- packages/core-sdk/src/utils/utils.ts
- packages/core-sdk/test/integration/ipAccount.test.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/integration/license.test.ts
- packages/core-sdk/test/integration/permission.test.ts
- packages/core-sdk/test/integration/royalty.test.ts
- packages/core-sdk/test/unit/resources/ipAccount.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/license.test.ts
- packages/core-sdk/test/unit/utils/sign.test.ts
- packages/core-sdk/test/unit/utils/utils.test.ts
- pnpm-lock.yaml
- Fix issue [[Bug] Return a list of license token id when users mint multiple tokens at the same time](https://github.com/storyprotocol/sdk/issues/194)
- Refactor signature including getPermissionSignature and call spg without metadata
- Fix issue for workflow fail
> Refactor signature and getAddress method

- packages/core-sdk/package.json
- packages/core-sdk/src/index.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/resources/nftClient.ts
- packages/core-sdk/src/resources/permission.ts
- packages/core-sdk/src/resources/royalty.ts
- packages/core-sdk/src/types/common.ts
- packages/core-sdk/src/types/resources/license.ts
- packages/core-sdk/src/types/resources/nftClient.ts
- packages/core-sdk/src/types/resources/royalty.ts
- packages/core-sdk/src/utils/sign.ts
- packages/core-sdk/test/integration/ipAccount.test.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/nftClient.test.ts
- packages/core-sdk/test/unit/resources/permission.test.ts
- packages/core-sdk/test/unit/utils/sign.test.ts
- pnpm-lock.yaml
- Fix export type issue
- Export signature method
- Modify calling signTypedData by wallet client, fix issue [Error when adding metadata in .register function with metamask](https://github.com/storyprotocol/sdk/issues/204)
> Export signature method

- README.md
- packages/core-sdk/README.md
- packages/core-sdk/package.json
- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/index.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/src/utils/utils.ts
- packages/core-sdk/test/integration/ipAccount.test.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/integration/license.test.ts
- packages/core-sdk/test/integration/permission.test.ts
- packages/core-sdk/test/integration/royalty.test.ts
- packages/core-sdk/test/integration/utils/util.ts
- packages/core-sdk/test/unit/client.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/core-sdk/test/unit/utils/sign.test.ts
- packages/core-sdk/test/unit/utils/utils.test.ts
- packages/wagmi-generator/wagmi.config.ts
* Add mintAndRegisterIpAndMakeDerivative in ipAsset
* Bump up sdk to 1.0.0-rc.18
* Rename storyTestnet to iliad about the related files'
> release rc.18

- packages/core-sdk/package.json
- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/src/utils/utils.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/integration/utils/mockERC20.ts
- packages/core-sdk/test/integration/utils/util.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/react-sdk/generator/index.js
- packages/react-sdk/src/resources/useDispute.ts
- packages/react-sdk/src/resources/useIpAccount.ts
- packages/react-sdk/src/resources/useIpAsset.ts
- packages/react-sdk/src/resources/useLicense.ts
- packages/react-sdk/src/resources/useNftClient.ts
- packages/react-sdk/src/resources/usePermission.ts
- packages/react-sdk/src/resources/useRoyalty.ts
- packages/react-sdk/test/integration/useDispute.test.ts
- packages/react-sdk/test/integration/useIpAccount.test.ts
- packages/react-sdk/test/integration/useIpAsset.test.ts
- packages/react-sdk/test/integration/useLicense.test.ts
- packages/react-sdk/test/integration/useNftClient.test.ts
- packages/react-sdk/test/integration/usePermission.test.ts
- packages/react-sdk/test/integration/useRoyalty.test.ts
- packages/react-sdk/test/integration/utils/util.ts
- packages/wagmi-generator/wagmi.config.ts
- Add nftMetadata into IPMetadata structure
- Bump up sdk to 1.0.0-rc.19
-  Update public testnet information
> Add nftMetadata into IPMetadata structure

- packages/core-sdk/package.json
- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/src/utils/utils.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/integration/utils/mockERC20.ts
- packages/core-sdk/test/integration/utils/util.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/react-sdk/generator/index.js
- packages/react-sdk/src/resources/useDispute.ts
- packages/react-sdk/src/resources/useIpAccount.ts
- packages/react-sdk/src/resources/useIpAsset.ts
- packages/react-sdk/src/resources/useLicense.ts
- packages/react-sdk/src/resources/useNftClient.ts
- packages/react-sdk/src/resources/usePermission.ts
- packages/react-sdk/src/resources/useRoyalty.ts
- packages/react-sdk/test/integration/useDispute.test.ts
- packages/react-sdk/test/integration/useIpAccount.test.ts
- packages/react-sdk/test/integration/useIpAsset.test.ts
- packages/react-sdk/test/integration/useLicense.test.ts
- packages/react-sdk/test/integration/useNftClient.test.ts
- packages/react-sdk/test/integration/usePermission.test.ts
- packages/react-sdk/test/integration/useRoyalty.test.ts
- packages/react-sdk/test/integration/utils/util.ts
- packages/wagmi-generator/wagmi.config.ts
* Add nftMetadata into struct IPMetadata
* Bump up sdk to 1.0.0-rc.19
* Update public information
> rc 19 release

- packages/core-sdk/src/index.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- Remove useless code for nftMetadata
- Export IpCreator, IpMetadata
> Remove useless code for nftMetadata

- packages/core-sdk/package.json
- packages/core-sdk/src/index.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/src/utils/getLicenseTermsByType.ts
- packages/core-sdk/test/unit/utils/getLicenseTermsByType.test.ts
> Bp/sdk pr 4 (#245)

- packages/core-sdk/package.json
- packages/core-sdk/src/index.ts
- packages/core-sdk/src/resources/dispute.ts
- packages/core-sdk/src/resources/ipAccount.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/resources/nftClient.ts
- packages/core-sdk/src/resources/permission.ts
- packages/core-sdk/src/resources/royalty.ts
- packages/core-sdk/src/types/options.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/test/integration/ipAccount.test.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/integration/royalty.test.ts
- packages/core-sdk/test/unit/resources/ipAccount.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- Refactor generateIpMetadata and generateCreatorMetadata
- Add other parameter into waitForTransactionReceipt
- Bump up version to 1.0.0-rc.22
> Refactor generateIpMetadata and generateCreatorMetadata

- packages/core-sdk/package.json
- packages/core-sdk/src/index.ts
- packages/core-sdk/src/resources/dispute.ts
- packages/core-sdk/src/resources/ipAccount.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/resources/nftClient.ts
- packages/core-sdk/src/resources/permission.ts
- packages/core-sdk/src/resources/royalty.ts
- packages/core-sdk/src/types/options.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/test/integration/ipAccount.test.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/integration/royalty.test.ts
- packages/core-sdk/test/unit/resources/ipAccount.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
* Refactor generateIpMetadata and generateCreatorMetadata
* Update ipAsset type
* Delete useless code
* Modify annotation format
* Remove useless code
* Remove integration test from workflow
* Add other parameter into waitForTransactionReceipt
* Remove useless code
* Bump up version to 1.0.0-rc.22
> Add extra parameters in waitForTransactionReceipt

- packages/core-sdk/package.json
- packages/core-sdk/src/index.ts
Bump up version to @story-protocol/[core-sdk@1.1.0-stable](mailto:core-sdk@1.1.0-stable)
Export RegisterPILTermsRequest type
Please make `dev_v1.1` and `v1.1` protect branches which cannot directly merge.
> Bump up version to @story-protocol/core-sdk@1.1.0-stable

- packages/core-sdk/package.json
- packages/core-sdk/src/index.ts
- Bump up version to 1.1.0-stable
> Bump up v1.1.0 stable

- packages/core-sdk/package.json
- packages/core-sdk/src/index.ts
* Export RegisterPILTermsRequest type
* Bump up version to 1.1.0-stable
Example:
- 2. ...
Example: 
- 2. ...
> Bump up v1.1.0 stable (#281)

- packages/core-sdk/package.json
- temporary skip integration tests
> Skip integration tests

- packages/core-sdk/package.json
> Bump up sdk to v1.2.0-rc.0

- .github/workflows/publish-package.yaml
- packages/core-sdk/package.json
* Bump up sdk to v1.2.0-rc.0 (#298)
* Update workflow
* Extract variables into env
* Update package name
Example:
- 2. ...
Example: 
- 2. ...
> Update workflow (#303)

- packages/core-sdk/package.json
Bump up sdk version to 1.2.0-rc.1
> Bump up sdk version to 1.2.0-rc.1

- packages/core-sdk/src/resources/ipAsset.ts
Example:
- 2. ...
Example: 
- 2. ...
> Test branch

- .github/workflows/pr-merge.yaml
- test_file.txt
Example:
- 2. ...
Example: 
- 2. ...
> Origin/dev polania/workflows test

- packages/core-sdk/src/resources/nftClient.ts
- packages/core-sdk/test/integration/dispute.test.ts
- packages/core-sdk/test/integration/group.test.ts
- packages/core-sdk/test/integration/ipAccount.test.ts
- packages/core-sdk/test/integration/nftClient.test.ts
* Updated and added integration tests for the following modules:
- dispute
- group
- ipAccount
- nftClient
* Improved error handling for NFTCollection
> Added v1.3 Coverage

- packages/core-sdk/package.json
- packages/core-sdk/test/integration/dispute.test.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/integration/license.test.ts
- packages/core-sdk/test/integration/permission.test.ts
- packages/core-sdk/test/integration/royalty.test.ts
- Expands coverage by adding test cases to:
* dispute
* ipAsset
* permission 
* royalty
- Changes name of some test cases
- Add coverage metrics to integration tests
> CoreSDK Integration Tests Added

- packages/core-sdk/package.json
- packages/core-sdk/test/integration/ipAsset.test.ts
* `ipAsset` to match new release
* Integration tests' coverage check removed
> Update test cases + Removed coverage check

- packages/core-sdk/test/integration/ipAsset.test.ts
Minor debugging for dl/aeneid-support branch
> Aeneid Support Debug

- packages/core-sdk/.vscode/launch.json
- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/client.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/src/types/utils/contract.ts
- packages/core-sdk/src/types/utils/erc20.ts
- packages/core-sdk/src/types/utils/wip.ts
- packages/core-sdk/src/utils/contract.ts
- packages/core-sdk/src/utils/erc20.ts
- packages/core-sdk/src/utils/utils.ts
- packages/core-sdk/src/utils/wipFeeUtils.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/integration/utils/util.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/core-sdk/test/unit/testUtils.ts
- packages/core-sdk/test/unit/utils/wipFeeUtils.test.ts
- packages/wagmi-generator/wagmi.config.ts
> feat: added auto wip conversion for ipAssets

- packages/core-sdk/package.json
- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/permission.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/src/types/utils/wip.ts
- packages/core-sdk/src/utils/sign.ts
- packages/core-sdk/test/integration/dispute.test.ts
- packages/core-sdk/test/integration/ipAccount.test.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/integration/license.test.ts
- packages/core-sdk/test/integration/royalty.test.ts
- packages/core-sdk/test/integration/utils/util.ts
- packages/core-sdk/test/integration/wip.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
> Fix integration tests

- packages/core-sdk/src/index.ts
Export license config and license terms data. resolves #440.
> chore: export license config and license terms data

- .github/CODEOWNERS
CONTEXT
Add @bonnie57 as reviewer per request from Draco.
> feat: add bonnie as reviewer

- packages/core-sdk/test/unit/resources/ipAsset.test.ts
Fix broken unit test that was missed.
> fix ipAsset ip metadata unit test

- packages/core-sdk/src/resources/group.ts
- packages/core-sdk/src/resources/ipAccount.ts
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/src/resources/nftClient.ts
- packages/core-sdk/src/resources/permission.ts
- packages/core-sdk/src/resources/royalty.ts
- packages/core-sdk/src/utils/sign.ts
- packages/core-sdk/src/utils/utils.ts
- packages/core-sdk/test/unit/resources/group.test.ts
- packages/core-sdk/test/unit/resources/ipAccount.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/license.test.ts
- packages/core-sdk/test/unit/resources/nftClient.test.ts
- packages/core-sdk/test/unit/resources/royalty.test.ts
- packages/core-sdk/test/unit/utils/utils.test.ts
> Remove getAddress method

- packages/core-sdk/src/constants/common.ts
- packages/core-sdk/src/index.ts
- packages/core-sdk/test/unit/resources/permission.test.ts
close https://github.com/storyprotocol/sdk/issues/387
> perf: use `zeroAddress` instead of `AddressZero` & remove `HashZero`

- packages/core-sdk/test/integration/dispute.test.ts
This PR updates the SDK to implement the new `bond` limits on `aeneid`
> New `bond` limits fix

- packages/core-sdk/src/client.ts
- packages/core-sdk/src/resources/dispute.ts
- packages/core-sdk/src/types/config.ts
- Modify the `disputeAssertion` method description
- Add the `chainId` inline doc.
> Improve document

- packages/core-sdk/test/integration/dispute.test.ts
- packages/core-sdk/test/integration/license.test.ts
- packages/core-sdk/test/integration/royalty.test.ts
- packages/core-sdk/test/integration/utils/BIP32.ts
1. `Claimer` is the owner wallet address
2. `Claimer` is the third wallet address
3. `Claimer` is the `Ip id`
> Add more test case for batchClaimAllRevenue

- packages/core-sdk/src/abi/oov3Abi.ts
- packages/core-sdk/src/resources/dispute.ts
- packages/core-sdk/src/types/resources/dispute.ts
- packages/core-sdk/src/utils/oov3.ts
- packages/core-sdk/test/integration/dispute.test.ts
- packages/core-sdk/test/unit/resources/dispute.test.ts
- Add minimum bond check
- Make `bond` optional and use minimum bond as default value.
> Add minimum bond in raiseDispute

- packages/core-sdk/package.json
This PR bumps the SDK version to 1.3.1-beta
> Bump up version to v1.3.1-beta

- packages/core-sdk/src/abi/generated.ts
- packages/core-sdk/src/resources/group.ts
- packages/core-sdk/src/types/resources/group.ts
- packages/core-sdk/test/integration/group.test.ts
- packages/core-sdk/test/unit/resources/group.test.ts
- packages/wagmi-generator/wagmi.config.ts
Add [remove](https://github.com/storyprotocol/protocol-core-v1/blob/main/contracts/modules/grouping/GroupingModule.sol#L207) IP Assets from a group
> Add removeIpsFromGroup method

- packages/core-sdk/package.json
This PR bumps the SDK version to 1.3.1
> Bump up version to v1.3.1

- .github/CODEOWNERS
This PR includes Yao and Meng as repo reviewers.
> Update Code Owners List

- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/test/integration/dispute.test.ts
This PR adds integration tests for the new Dispute Module functionality introduced in PR #521.
> Dispute Module Integration Tests - DisputeTargetTag

- packages/core-sdk/src/resources/license.ts
- packages/core-sdk/test/integration/license.test.ts
This PR adds integration tests for the new License Module functionality introduced in PR https://github.com/storyprotocol/sdk/pull/515.
> License Module Integration Tests - Creative Commons

- packages/core-sdk/package.json
- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/test/integration/dispute.test.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/tsconfig.json
This PR allows License Terms ID for `mintAndRegisterIpAssetWithPilTerms`
https://www.notion.so/storyprotocol/Allow-License-Terms-ID-for-Attachment-Methods-1ea051299a5480b388d2ca6318e29507
> Allow License Terms ID for `mintAndRegisterIpAssetWithPilTerms`

- packages/core-sdk/test/integration/dispute.test.ts
- packages/core-sdk/test/integration/group.test.ts
- packages/core-sdk/test/integration/ipAccount.test.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/integration/license.test.ts
- packages/core-sdk/test/integration/nftClient.test.ts
- packages/core-sdk/test/integration/permission.test.ts
- packages/core-sdk/test/integration/royalty.test.ts
- packages/core-sdk/test/integration/utils/BIP32.ts
- packages/core-sdk/test/integration/utils/generateHex.ts
- packages/core-sdk/test/integration/utils/util.ts
- packages/core-sdk/test/integration/wip.test.ts
1.  Fix lint issues in the integration tests
2. Remove the encode test and off-chain test case
#558
> Fix integration tests lint issue

- packages/core-sdk/src/types/resources/permission.ts
- packages/core-sdk/test/integration/ipAccount.test.ts
- Add core signature validation tests
- Add wrong data/address signature tests
- Add zero-value transaction test
> test(ipAccount): enhance executeWithSig test

- packages/core-sdk/src/resources/ipAsset.ts
- packages/core-sdk/src/types/resources/ipAsset.ts
- packages/core-sdk/test/integration/ipAsset.test.ts
- packages/core-sdk/test/unit/resources/ipAsset.test.ts
- Add more examples in the doc of how to call  the `registerIpAsset` method
- Add unit tests to the coverage optional value
- Add more meaningful document
- Add a group about mint and minted NFT in the registerIpAsset integration test
> Enhance the re-design register method
